//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutologiaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public int MANUFACTOR { get; set; }
        public int MODEL { get; set; }
        public int SUB_MODEL { get; set; }
        public int YEAR { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public Nullable<int> MAIN_TYPE { get; set; }
        public Nullable<int> SUB_TYPE { get; set; }
        public Nullable<int> LICENSE { get; set; }
        public Nullable<int> SEATS { get; set; }
        public Nullable<int> DORS { get; set; }
        public Nullable<int> FUEL_TYPE { get; set; }
        public int GEER { get; set; }
        public Nullable<int> SIZE { get; set; }
        public Nullable<int> TRUNK { get; set; }
        public Nullable<int> ACCESSORY { get; set; }
        public Nullable<int> RESPONSE { get; set; }
        public Nullable<int> SEAT_5 { get; set; }
        public Nullable<int> VISUAL_SPACE { get; set; }
        public Nullable<int> ROAD { get; set; }
        public Nullable<int> MAINTANANCE { get; set; }
        public Nullable<int> RELIABILITY { get; set; }
        public Nullable<int> TRADE { get; set; }
        public Nullable<int> VALUE { get; set; }
        public Nullable<int> SECURE { get; set; }
        public Nullable<int> GAS_COMPATIBLE { get; set; }
        public Nullable<int> IGNITION { get; set; }
        public Nullable<int> HEAT_STAND { get; set; }
        public Nullable<int> SMOKERS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> MULTI_DRIVER { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string OPPINION_FOR { get; set; }
        public string OPPINION_AGAINST { get; set; }
        public string LINKS { get; set; }
        public Nullable<int> AVIRUT_SHETAH { get; set; }
        public string UNIQUE_IDENTIFIER { get; set; }
        public string SUB_MODEL_DESC { get; set; }
        public string YEAR_DESC { get; set; }
        public string COUNTRY_DESC { get; set; }
        public string MAIN_TYPE_DESC { get; set; }
        public string SUB_TYPE_DESC { get; set; }
        public string LICENSE_DESC { get; set; }
        public string SEATS_DESC { get; set; }
        public string FUEL_TYPE_DESC { get; set; }
        public string GEER_DESC { get; set; }
        public string SIZE_DESC { get; set; }
        public string TRUNK_DESC { get; set; }
        public string RESPONSE_DESC { get; set; }
        public string SEAT_5_DESC { get; set; }
        public string ROAD_DESC { get; set; }
        public string MAINTANANCE_DESC { get; set; }
        public string RELIABILITY_DESC { get; set; }
        public string TRADE_DESC { get; set; }
        public string VALUE_DESC { get; set; }
        public string SECURE_DESC { get; set; }
        public string GAS_COMPATIBLE_DESC { get; set; }
        public string IGNITION_DESC { get; set; }
        public string HEAT_STAND_DESC { get; set; }
        public string SMOKERS_DESC { get; set; }
        public string AVIRUT_SHETAH_DESC { get; set; }
        public string MULTI_DRIVER_DESC { get; set; }
        public string PERCEPTION_DESC { get; set; }
        public string VISUAL_SPACE_DESC { get; set; }
        public string DRIVER_DESC { get; set; }
        public Nullable<int> BODY { get; set; }
        public string BODY_DESC { get; set; }
        public string DORS_DESC { get; set; }
        public string ACCESSORY_DESC { get; set; }
        public Nullable<int> FUEL_CONSUME { get; set; }
        public string FEUL_CONSUME_DESC { get; set; }
    
        public virtual CarManufactors CarManufactors { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual CarSubModel CarSubModel { get; set; }
    }
}
