//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutologiaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsEx
    {
        public int CAR_ID { get; set; }
        public int MAIN_LOOKUP_ID { get; set; }
        public int LOOKUP_ID { get; set; }
        public string LOOKUP_VALUE { get; set; }
    }
}
