//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutologiaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupDetails
    {
        public int ID { get; set; }
        public int MAIN_LOOKUP_ID { get; set; }
        public string VALUE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
    
        public virtual MainLookup MainLookup { get; set; }
    }
}
