//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutologiaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainLookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainLookup()
        {
            this.LookupDetails = new HashSet<LookupDetails>();
        }
    
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> MENU_REF_ID { get; set; }
        public string MANUAL { get; set; }
        public string VALUES_MANUAL { get; set; }
        public Nullable<int> ORDER { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookupDetails> LookupDetails { get; set; }
    }
}
