//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutologiaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandatoryQuestions
    {
        public int TYPE_ID { get; set; }
        public int QUESTION_ID { get; set; }
        public Nullable<bool> IS_MANDATORY { get; set; }
    }
}
