//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutologiaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsAnswers
    {
        public int TYPE_ID { get; set; }
        public int QUESTION_ID { get; set; }
        public int ANSWER_ID { get; set; }
        public int ORDER { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Answers Answers { get; set; }
    }
}
